---
appConfig:
  port: 5065
  env: charite
  config_center_enabled: true
  config_center_base_url: http://common.utility:5062/
  srv_namespace: service_notification
  RDS_DB_NAME: notifications
  RDS_SECRET_REF: opsdb-indoc-vre

deploymentAnnotations:
  "sidecar.jaegertracing.io/inject": "true"

image:
  repository: registry.bihealth.org:443/vre/service_notification
  tag: 103
  pullPolicy: Always

fullnameOverride: notification
container:
  port: 5065

service:
  type: ClusterIP
  port: 5065
  targetPort: 5065

extraEnv:
  namespace: utility
  VAULT_URL: "https://vault.vault:8200/v1/vre/app/config"
  VAULT_CRT: "/etc/vre/pki/ca.crt"

extraEnvYaml:
  - name: VAULT_TOKEN
    valueFrom:
      secretKeyRef:
        name: vault-secret
        key: token

readinessProbe:
  failureThreshold: 3
  initialDelaySeconds: 5
  periodSeconds: 10
  successThreshold: 1
  tcpSocket:
    port: 5065

replicaCount: 1

updateStrategy:
  rollingUpdate:
    maxSurge: 1
    maxUnavailable: 33%
  type: RollingUpdate

imagePullSecrets:
  - name: regcred
    namespace: utility

extraVolumes:
  - name: vre-pki-root
    configMap:
      name: vre-root-certificate-bundle-utility
      items:
        - key: ca.crt
          path: ca.crt

extraVolumeMounts:
  - name: vre-pki-root
    mountPath: /etc/vre/pki
