---
appConfig:
  port: 5082
  env: charite
  config_center_enabled: true
  contig_center_base_url: http://common.utility:5062/
  srv_namespace: service_encryption

image:
  repository: registry.bihealth.org:443/vre/service_encryption
  tag: 16
  pullPolicy: Always

fullnameOverride: encryption
container:
  port: 5082

service:
  type: ClusterIP
  port: 5082
  targetPort: 5082

extraEnv:
  VAULT_URL: "https://vault.vault:8200/v1/vre/app/config"
  VAULT_CRT: "/etc/vre/pki/ca.crt"
  KEYCLOAK_PATH: "/vre/auth/realms/vre/protocol/openid-connect/token"

extraEnvYaml:
  - name: VAULT_TOKEN
    valueFrom:
      secretKeyRef:
        name: vault-secret
        key: token

readinessProbe:
  failureThreshold: 3
  initialDelaySeconds: 5
  periodSeconds: 10
  successThreshold: 1
  tcpSocket:
    port: 5082

replicaCount: 1

updateStrategy:
  rollingUpdate:
    maxSurge: 1
    maxUnavailable: 33%
  type: RollingUpdate

imagePullSecrets:
  - name: "test"
    namespace: "vre"

extraVolumes:
  - name: vre-pki-root
    configMap:
      name: vre-root-certificate-bundle-utility
      items:
        - key: ca.crt
          path: ca.crt

extraVolumeMounts:
  - name: vre-pki-root
    mountPath: /etc/vre/pki
