---
appConfig:
  env: charite
  config_center_enabled: true
  ALEMBIC_CONFIG: "/app/alembic.ini"
  OPEN_TELEMETRY_ENABLED: "TRUE"
  DATASET_FILE_FOLDER: "data"
  DATASET_SCHEMA_FOLDER: "schema"
  DATASET_CODE_REGEX: "^[a-z0-9]{3,32}$"
  KEYCLOAK_URL: "http://keycloak.utility:8080/vre/auth/realms/vre/protocol/openid-connect/token"
  REDIS_HOST: "redis-master.utility"
  REDIS_PORT: "6379"
  REDIS_DB: "0"
  DOWNLOAD_TOKEN_EXPIRE_AT: "5"
  MAX_PREVIEW_SIZE: "500000"
  ESSENTIALS_NAME: "essential.schema.json"
  ESSENTIALS_TPL_NAME: "Essential"

deploymentAnnotations:
  "sidecar.jaegertracing.io/inject": "true"

fullnameOverride: dataset

image:
  repository: registry.bihealth.org:443/vre/service_dataset
  tag: 242
  pullPolicy: Always

container:
  port: 5081

extraEnv:
  VAULT_URL: "https://vault.vault:8200/v1/vre/app/config"
  VAULT_CRT: "/etc/vre/pki/ca.crt"

extraEnvYaml:
  - name: VAULT_TOKEN
    valueFrom:
      secretKeyRef:
        name: vault-secret
        key: token

service:
  type: ClusterIP
  port: 5081

readinessProbe:
  failureThreshold: 3
  initialDelaySeconds: 5
  periodSeconds: 10
  successThreshold: 1
  tcpSocket:
    port: 5081

replicaCount: 1

updateStrategy:
  rollingUpdate:
    maxSurge: 1
    maxUnavailable: 33%
  type: RollingUpdate

imagePullSecrets:
  - name: regcred
    namespace: utility

extraVolumes:
  - name: vre-pki-root
    configMap:
      name: vre-root-certificate-bundle-utility
      items:
        - key: ca.crt
          path: ca.crt

extraVolumeMounts:
  - name: vre-pki-root
    mountPath: /etc/vre/pki
