---
appConfig:
  env: "charite"
  config_center_enabled: true
  config_center_base_url: "http://common.utility:5062/"

deploymentAnnotations:
  "sidecar.jaegertracing.io/inject": "true"

image:
  repository: registry.bihealth.org:443/vre/service_queue/producer
  tag: 104
  pullPolicy: Always

replicaCount: 1

fullnameOverride: queue-producer

container:
  port: 6060

service:
  type: ClusterIP
  port: 6060
  targetPort: 6060

extraEnv:
  VAULT_URL: "https://vault.vault:8200/v1/vre/app/config"
  VAULT_CRT: "/etc/vre/pki/ca.crt"
  data_storage: "/vre-data"
  DCM_PROJECT: "generate"
  DCM_PROJECT_ID: "generate_id"

extraEnvYaml:
  - name: VAULT_TOKEN
    valueFrom:
      secretKeyRef:
        name: vault-secret
        key: token

# volumes:
#   name: nfsvol
#   mountPath: /data/vre-storage
#   claimName: greenroom-storage

resources:
  requests:
    memory: "1000Mi"
    cpu: "100m"
  limits:
    memory: "1000Mi"
    cpu: "100m"

readinessProbe:
  tcpSocket:
    port: 6060
  initialDelaySeconds: 5
  periodSeconds: 10
updateStrategy:
  rollingUpdate:
    maxSurge: 1
    maxUnavailable: 33%
  type: RollingUpdate

imagePullSecrets:
  - name: regcred
    namespace: greenroom

extraVolumes:
  - name: vre-pki-root
    configMap:
      name: vre-root-certificate-bundle-greenroom
      items:
        - key: ca.crt
          path: ca.crt

extraVolumeMounts:
  - name: vre-pki-root
    mountPath: /etc/vre/pki
