---
appConfig:
  port: 5077
  env: "charite"
  config_center_enabled: true
  config_center_base_url: http://common.utility:5062/
  srv_namespace: service_download

deploymentAnnotations:
  "sidecar.jaegertracing.io/inject": "true"

image:
  repository: registry.bihealth.org:443/vre/service_download
  tag: 198
  pullPolicy: Always

imagePullSecrets:
  - name: regcred
    namespace: vre

fullnameOverride: download

container:
  port: 5077

service:
  type: ClusterIP
  port: 5077
  targetPort: 5077

extraEnv:
  VAULT_URL: "https://vault.vault:8200/v1/vre/app/config"
  VAULT_CRT: "/etc/vre/pki/ca.crt"

extraEnvYaml:
  - name: VAULT_TOKEN
    valueFrom:
      secretKeyRef:
        name: vault-secret
        key: token

readinessProbe:
  failureThreshold: 3
  initialDelaySeconds: 5
  periodSeconds: 10
  successThreshold: 1
  tcpSocket:
    port: 5077

replicaCount: 1

updateStrategy:
  rollingUpdate:
    maxSurge: 1
    maxUnavailable: 33%
  type: RollingUpdate

extraVolumes:
  - name: vre-pki-root
    configMap:
      name: vre-root-certificate-bundle-vre
      items:
        - key: ca.crt
          path: ca.crt

extraVolumeMounts:
  - name: vre-pki-root
    mountPath: /etc/vre/pki
